### ISSUE TITLE
name 'sha56' is not defined

### ISSUE THREAD

**Issue by simecky** [silvije2/topsee_seetong_onvif_python_motion_detect#1]
Maybe I do something wrong.... 

I am not find from suds-passworddigest-py3, I am installed missing deamon via pip3 install python_daemon - after that I am stopping getting error about mising module - "ImportError: No module named 'daemon'"

now script is runable , but from executing I am getting this error,which  i dont know how solve
`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/onvif/client.py", line 34, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/onvif/client.py", line 201, in wrapped
    return call(params, callback)
  File "/usr/local/lib/python3.5/dist-packages/onvif/client.py", line 191, in call
    ret = func(**params)
  File "/home/simi/.local/lib/python3.5/site-packages/suds/client.py", line 559, in __call__
    return client.invoke(args, kwargs)
  File "/home/simi/.local/lib/python3.5/site-packages/suds/client.py", line 612, in invoke
    soapenv = binding.get_message(self.method, args, kwargs)
  File "/home/simi/.local/lib/python3.5/site-packages/suds/bindings/binding.py", line 118, in get_message
    content = self.headercontent(method)
  File "/home/simi/.local/lib/python3.5/site-packages/suds/bindings/binding.py", line 367, in headercontent
    content.append(wsse.xml())
  File "/home/simi/.local/lib/python3.5/site-packages/suds/wsse.py", line 80, in xml
    root.append(t.xml())
  File "/home/simi/.local/lib/python3.5/site-packages/suds_passworddigest/token.py", line 57, in xml
    p.setText(self.generate_digest())
  File "/home/simi/.local/lib/python3.5/site-packages/suds_passworddigest/token.py", line 34, in generate_digest
    self.setnonce()
  File "/home/simi/.local/lib/python3.5/site-packages/suds/wsse.py", line 143, in setnonce
    m = sha56()
NameError: name 'sha56' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "motion_detect.py", line 12, in <module>
    mycam = ONVIFCamera('192.168.10.5', 80, 'admin', '******')  # , no_cache=True)
  File "/usr/local/lib/python3.5/dist-packages/onvif/client.py", line 267, in __init__
    self.update_xaddrs()
  File "/usr/local/lib/python3.5/dist-packages/onvif/client.py", line 283, in update_xaddrs
    capabilities = self.devicemgmt.GetCapabilities({'Category': 'All'})
  File "/usr/local/lib/python3.5/dist-packages/onvif/client.py", line 36, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: name 'sha56' is not defined
`

**Comment by silvije2** [comment]
ok, I am using python3.8 but this is what you could try:

go to directory /usr/local/lib/python3.5/dist-packages/suds and edit file wsse.py

@@ -140,7 +140,7 @@
             s.append(self.username)
             s.append(self.password)
             s.append(Token.sysdate())
-            m = sha256()
+            m = sha56()
             m.update(':'.join(s).encode("utf-8"))
             self.nonce = m.hexdigest()
         else:

and lets see if it helps...

**Comment by silvije2** [comment]
ok, I am using python3.8 but this is what you could try:

go to directory /usr/local/lib/python3.5/dist-packages/suds and edit file wsse.py

```
@@ -140,7 +140,7 @@
             s.append(self.username)
             s.append(self.password)
             s.append(Token.sysdate())
+            m = sha256()
-            m = sha56()
             m.update(':'.join(s).encode("utf-8"))
             self.nonce = m.hexdigest()
         else:
```
and lets see if it helps...

**Comment by silvije2** [comment]
use recent python version
